### ISSUE TITLE
Error when searching for samples that are not uploaded to database

### ISSUE THREAD

**Issue by Shettland** [BU-ISCIII/relecov-platform#113]
Intranet's "Samples search" process gives an error when searching for a sample name of a sample that has not been uploaded to the database yet.

Screenshot of the error:
![image](https://github.com/BU-ISCIII/relecov-platform/assets/76519482/c45307bb-0f27-4135-a15c-8968275ea8d7)

**Comment by luissian** [comment]
Already solved
