### ISSUE TITLE
Remove authentication to access homepage

### ISSUE THREAD

**Issue by Shettland** [BU-ISCIII/relecov-platform#115]
It does not make sense that the home page requires authentication because then no user can see that the platform is functional. Therefore, it would be nice to remove authentication from it, by deleting the decorator here:
https://github.com/BU-ISCIII/relecov-platform/blob/5797e933c9decdebe78108834b2243e1656ca8f6/relecov_core/views.py#L97-L98

**Comment by luissian** [comment]
It was a mandatory requirement from one of the last meetings when presenting the platform.
Because they want to be sure that only people involve in the project have access.
