### ISSUE TITLE
`instal.sh` script triggers 'rsync no such file or directory' warnings

### ISSUE THREAD

**Issue by Daniel-VM** [BU-ISCIII/relecov-platform#117]
While cleaning up errors and warnings in the installation script, I encountered a section where I have some doubts. It seems there are two rsync commands that will always execute, correct? (Lines [606](https://github.com/BU-ISCIII/relecov-platform/blob/598687f57305bbed4d11a2b4b6357c51b59df628/install.sh#L606) and [625](https://github.com/BU-ISCIII/relecov-platform/blob/598687f57305bbed4d11a2b4b6357c51b59df628/install.sh#L625)).

The second rsync command (line [625](https://github.com/BU-ISCIII/relecov-platform/blob/598687f57305bbed4d11a2b4b6357c51b59df628/install.sh#L625)) causes these warnings because it enters a directory (https://github.com/BU-ISCIII/relecov-platform/blob/598687f57305bbed4d11a2b4b6357c51b59df628/install.sh#L608) where the specified files do not exist:
```
rsync: [sender] link_stat "/opt/relecov-platform/relecov_platform/README.md" failed: No such file or directory (2)
rsync: [sender] link_stat "/opt/relecov-platform/relecov_platform/LICENSE" failed: No such file or directory (2)
rsync: [sender] link_stat "/opt/relecov-platform/relecov_platform/test" failed: No such file or directory (2)
rsync: [sender] link_stat "/opt/relecov-platform/relecov_platform/conf" failed: No such file or directory (2)
rsync: [sender] link_stat "/opt/relecov-platform/relecov_platform/django_utils" failed: No such file or directory (2)
rsync: [sender] link_stat "/opt/relecov-platform/relecov_platform/django_plotly_dash" failed: No such file or directory (2)
rsync: [sender] link_stat "/opt/relecov-platform/relecov_platform/relecov_core" failed: No such file or directory (2)
rsync: [sender] link_stat "/opt/relecov-platform/relecov_platform/relecov_dashboard" failed: No such file or directory (2)
```
Additionally, the rsync command at line [625](https://github.com/BU-ISCIII/relecov-platform/blob/598687f57305bbed4d11a2b4b6357c51b59df628/install.sh#L625) looks for django_utils and django_plotly_dash, which are not present in the Git repository. Is this a typo, or are they there for a specific reason?

**Comment by saramonzon** [comment]
Something wrong there. The rsync in line 625 should not be needed, it is duplicated with line 606. Also the documents structure I think is copied from iskylims and it's not correct. 
My bad because I missed this during the PR review
