### ISSUE TITLE
In the main menu "Dashboard"  has a wrong format.

### ISSUE THREAD

**Issue by luissian** [BU-ISCIII/relecov-platform#118]
All options in the menu must have the same format

![image](https://user-images.githubusercontent.com/24755054/175807483-71ea08b0-07b2-4f4a-a066-9a6e49078f2f.png)

**Comment by luisiJavo** [comment]
Fixed
![image](https://user-images.githubusercontent.com/94523342/175924553-2f02bb0c-c081-4962-ab45-baa7cb27318d.png)

relecov_core/static/relecov_core/assets/css/main.css -> added class

**Comment by luisiJavo** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/94523342/175925512-5c373d9c-dc6d-400c-80b3-f79f4153941e.png)

relecov_core/static/relecov_core/assets/css/main.css-> added class
```
.dashboard_text{
  color: var(--bs-gray-600);
  text-decoration: none;
}
```
relecov_core/templates/relecov_core/base.html -> added
![image](https://user-images.githubusercontent.com/94523342/175925628-205c53a8-d126-4fd9-a05a-711c24113cd9.png)
