### ISSUE TITLE
Installation script improvements

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/relecov-platform#16]
## Instalation script enhancements
- [x] Add apache configuration for Ubuntu
- [x] Add apache configuration for CentOS
- [x] Add parameter conf for the script (--conf_file)
- [x] Add --dev parameter so develop branch is used in installation
- [x] Check if apache username is the same for centos and ubuntu
- [x] Add update parameter (--update)

## Configuration files needed
- [x] Create clean and updated template settings.
- [x] Create clean and updated upload_tables.txt
- [x] Create clean and update template install settings
- [x] Create clean and updated urls.py

## Manual
- [x] Create installation manual for UTIC

**Comment by luissian** [comment]
to check apache user type : 
`ps aux | egrep '(apache|httpd)'`
Apache user for:
-  ubuntu is "apache2
-  redhat is "apache"
