### ISSUE TITLE
Review and Update Lineages-VOC Dashboard Graphic JSON

### ISSUE THREAD

**Issue by Daniel-VM** [BU-ISCIII/relecov-platform#162]
On the Lineages-VOC Dashboard (http://relecov-platform.isciiides.es/dashboard/variants/lineagesVoc), no samples appear even when a valid period is selected. The Graphic JSON might be outdated. Review and update the JSON configuration to reflect the correct data.

**Comment by Shettland** [comment]
Fixed in https://github.com/BU-ISCIII/relecov-platform/pull/151
