### ISSUE TITLE
Add Documentation link to main menu

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/relecov-platform#209]
Documentation link is only added to the main page. It should be added to the main menu too.
![image](https://user-images.githubusercontent.com/3480206/194317206-56e9c612-a1da-4064-9e80-d4b79022b202.png)

**Comment by luissian** [comment]
Implemented in commit  2ad8419ce15ff0ac08803a9277426f699d6af0f0

![image](https://user-images.githubusercontent.com/24755054/194558162-5f8f7230-26bf-40bb-8023-2bfe821b547f.png)
