### ISSUE TITLE
Intranet: results visualization

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/relecov-platform#22]

**Comment by luissian** [comment]
The main page after login into intranet will show tabs with the sample information upload from laboratory to the platform.
Where **history** will have a bar diagram with dates and number of samples, **actions** : the  actions done on the last batch of samples. GISEAD and ENA the IDs of their smples

![image](https://user-images.githubusercontent.com/24755054/195016292-e21db0b9-e8c4-42e8-84b3-444a5a7e4fca.png)

**Comment by luissian** [comment]
implemented in the PR  https://github.com/BU-ISCIII/relecov-platform/pull/228
