### ISSUE TITLE
Relecov Wordpress: Lista de las entidades que financia Relecov

### ISSUE THREAD

**Issue by ErikaKvalem** [BU-ISCIII/relecov-platform#27]

**Comment by ErikaKvalem** [comment]
Según tengo entendido ECDC HERA https://www.ecdc.europa.eu/en/news-events/ecdc-supports-eueea-member-states-rapid-detection-sars-cov-2-variants

**Comment by ErikaKvalem** [comment]
Lo mismo que en el issue #30

**Comment by ErikaKvalem** [comment]
- [] Añadir desplegable en RELECOV SPAIN --> Contributors 
- [] Contributors: Relecov Partners 
- [] Contributors: Key Contributors 
- [] Contributors Managment team 
- [] Contributors: External collaborations

**Comment by ErikaKvalem** [comment]
Please @luisiJavo  help quitando las imagenes destacadas duplicadas

**Comment by ErikaKvalem** [comment]
Me reparto las tareas con Guille
- [ ] Mapa @GuilleGorines 
- [ ] Imagenes y partners @ErikaKvalem

**Comment by ErikaKvalem** [comment]
Solucionado la duplicidad de imagenes destacadas 
Falta también contenido para 
- [ ] Analysis 
- [ ] Reports 
- [ ] Contact (PRIORIZAR, mas facil)

**Comment by ErikaKvalem** [comment]
Muevo la fecha al 4 para tener todo esto antes de la reunión de bioinfo en caso de que se quiera enseñar

**Comment by saramonzon** [comment]
Ok, si se puede enseñar sería perfecto

**Comment by ErikaKvalem** [comment]
Feedback de María: 
- Está en conversaciones para averiguar los partners oficiales 

Esperamos que nos mande 
- La introducción,
- Los informes (ministerio, técnicos, ECDC hera, control de calidad entre otros )
- Información extra de contacto

**Comment by ErikaKvalem** [comment]
He añadido el contacto que me ha mandado maria pero habría que darle formato 
 [ ] Darle formato a la pagina de contacto

**Comment by ErikaKvalem** [comment]
FALTA (Por parte de respiratorios) 


- [ ] Lista de personas del "equipo coordinador" 
- [ ] Informes (ministerio, técnicos, ECDC HERA, control de calidad entre otros ). María quedó en enviarnos los para poner en la sección "REPORTS"

- [ ] "Fotos de relleno" para la sección de RELECOV Spain
