### ISSUE TITLE
include in configuration PublicDatabaseType data

### ISSUE THREAD

**Issue by luissian** [BU-ISCIII/relecov-platform#30]
To fetch the information for other instance of relevov platform execute:
./manage.py dumpdata relecov_core.PublicDatabaseType --indent 4 --natural-foreign > ~/Downloads/relecov_core_public_database_type.json

Then load on the new relecov platform instance using

./manage.py loaddata /relecov_core_public_database_type.json 

Because the table data it is just only load in a table without other references it works even if the pk does not start from 1.

**Comment by saramonzon** [comment]
Managed in issue #4
