### ISSUE TITLE
Relecov Wordpress: Contacto: Diferentes email/telefono dependiendo del propósito de la consulta  a RELECOV

### ISSUE THREAD

**Issue by ErikaKvalem** [BU-ISCIII/relecov-platform#32]

**Comment by Alema91** [comment]
[HERA-relecov contacts](https://docs.google.com/spreadsheets/d/1NfYPLhe_o4MoH6chonZFrb1wvCpsLmS5RlxHgdzgmq0/edit)

**Comment by ErikaKvalem** [comment]
Contactos de: 
Unidad Bioinformática
Laboratorio Microbiología
Unidad genómica
Gestión proyecto
Responsables
GRUPO DE TRABAJO Slack
GRUPO DE TRABAJO Drive

**Comment by Alema91** [comment]
https://docs.google.com/spreadsheets/d/1NfYPLhe_o4MoH6chonZFrb1wvCpsLmS5RlxHgdzgmq0/edit#gid=583995449

Creo que en la tabla esta todo.
