### ISSUE TITLE
Relecov QC report

### ISSUE THREAD

**Issue by Alema91** [BU-ISCIII/relecov-platform#38]
REPORT OF THE RELECOV QUALITY CONTROL

**Comment by ErikaKvalem** [comment]
Estamos trabajando en ello. 

https://docs.google.com/document/d/1yafyp4XxzHAPyrc8npNVld9OiXCXmKUF/edit#

**Comment by ErikaKvalem** [comment]
He comentado la mitad aprox de las gráficas

**Comment by Alema91** [comment]
He compartido las gráficas y he mejorado alguna visualizacion (mutaciones y variant callers).

**Comment by saramonzon** [comment]
Done first draft, 

- [ ] review @saramonzon

**Comment by Alema91** [comment]
- [ ] Reformat lineages plot with Sonia values

**Comment by Alema91** [comment]
Almost done. Reviewed is needed.

**Comment by Alema91** [comment]
Problems with group code. Need to reorganize all the tables.

**Comment by Alema91** [comment]
All changes made the novo.

**Comment by Alema91** [comment]
Sended to Sonia and waiting for her feedback.

**Comment by ErikaKvalem** [comment]
El QC report fue enviado el viernes 6 de MAYO 2022
