### ISSUE TITLE
Relecov Wordpress: Lista de las entidades que financia Relecov

### ISSUE THREAD

**Issue by ErikaKvalem** [BU-ISCIII/relecov-platform#66]

**Comment by ErikaKvalem** [comment]
Según tengo entendido ECDC HERA https://www.ecdc.europa.eu/en/news-events/ecdc-supports-eueea-member-states-rapid-detection-sars-cov-2-variants

**Comment by ErikaKvalem** [comment]
Lo mismo que en el issue BU-ISCIII/relecov-platform#63

**Comment by ErikaKvalem** [comment]
- [x] Añadir desplegable en RELECOV SPAIN --> Contributors 
- [x] Contributors: Relecov Partners 
- [x] Contributors: Key Contributors 
- [ ] Contributors Managment team 
- [ ] Contributors: External collaborations 
- [x] Contact-> Cada punto en el mapa redirige a una nueva pagina donde hay: pequeña info sobre el centro, web,  y se listan los participantes del centro + foto del centro

**Comment by ErikaKvalem** [comment]
He añadido la lista de contributorstengo que añadir una imagen por organización y sus colaboradores. 
Arreglar probelams con wordpress editor y elementor editor

**Comment by ErikaKvalem** [comment]
Solucionado la duplicidad de imagenes destacadas 
Falta también contenido para 
- [ ] Analysis 
- [ ] Reports 
- [x] Contact (PRIORIZAR, mas facil)

**Comment by ErikaKvalem** [comment]
Muevo la fecha al 4 para tener todo esto antes de la reunión de bioinfo en caso de que se quiera enseñar

**Comment by saramonzon** [comment]
Ok, si se puede enseñar sería perfecto

**Comment by ErikaKvalem** [comment]
Feedback de María: 
- Está en conversaciones para averiguar los partners oficiales 

Esperamos que nos mande 
- La introducción,
- Los informes (ministerio, técnicos, ECDC hera, control de calidad entre otros ) para la parte de REPORT
- Información extra de contacto 

Falta la parte de:
- [ ]  ANALYSIS @saramonzon ¿se puede avanzar con ello? 
- [x] Coordinating team 
- [x] Contributors: External collaborations
- [ ] Fotos de relleno y de los equipos del ISCIII 



He borrado dos issues de Relecov Wordpress para no liarme

**Comment by ErikaKvalem** [comment]
He añadido el contacto que me ha mandado maria pero habría que darle formato 
-  [ ] Darle formato a la pagina de contacto

**Comment by ErikaKvalem** [comment]
FALTA (Por parte de respiratorios) 


- [ ] Lista de personas del "equipo coordinador" 
- [ ] Informes (ministerio, técnicos, ECDC HERA, control de calidad entre otros ). María quedó en enviarnos los para poner en la sección "REPORTS"

- [ ] "Fotos de relleno" para la sección de RELECOV Spain
