### ISSUE TITLE
Typos and format mistakes found in platform

### ISSUE THREAD

**Issue by GuilleGorines** [BU-ISCIII/relecov-platform#8]
Here I gather all the typos I have found in the relecov wordpress so far!

-1: In the bottom bar,  there is a typo on "2022" 
![image](https://user-images.githubusercontent.com/60110848/213180036-4facf1fa-2202-4569-b737-02a8a2ced56b.png)

-2: In the "news" section, the address does not match the info given in the "contact" tab (in both versions)
![image](https://user-images.githubusercontent.com/60110848/213180453-0762e1c0-3929-4dba-aeab-1686d61553c2.png)

-3: In the "contributors" page (english ver), there is a "ç" typo
![image](https://user-images.githubusercontent.com/60110848/213180925-f24102e7-b1a7-4731-b626-4f01fb039ec4.png)

-4: in the main page (english ver), when clicking on the "ANALYSIS" button, the redirection goes to "news" instead of "analysis". 
![image](https://user-images.githubusercontent.com/60110848/213182780-b2c0804e-0c01-4514-acb5-cb2115b2036e.png)

-5: no category assigned to the news displayed in the main page (both versions)
![image](https://user-images.githubusercontent.com/60110848/213183036-3d5d3dee-7498-44bc-9cb0-b4cfd8ab0402.png)

-6: not 100% sure about this one, but I think the contact in the CNM and the ISCIII have different font colours (ISCIII looks lighter?). I see this in both versions.
![image](https://user-images.githubusercontent.com/60110848/213183310-6bdbca93-89e0-4a38-8f68-60cf1d97c6f9.png)

**Comment by luissian** [comment]
this is not an issue for relecov platform
