### ISSUE TITLE
Generar Nextstrain

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/relecov-platform#9]

**Comment by luissian** [comment]
Nextstrain is available through index page.
![image](https://user-images.githubusercontent.com/24755054/215179305-97401a99-f4c7-4919-af36-a7862c8c51d0.png)
- New parameter is configured in database "NEXTSTRAIN_URL" to change dynamically the server location
- Service configuration file created for Nextstrain app

**Comment by luissian** [comment]
Configuration service file create to start nextstrain as service
